package com.akirachix.myreaderblog

import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.recyclerview.widget.LinearLayoutManager
import com.akirachix.myreaderblog.databinding.ActivityMainBinding

class MainActivity : AppCompatActivity() {
    lateinit var binding: ActivityMainBinding
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding=ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        binding.rvInfo.layoutManager=LinearLayoutManager(this)
        displayAuthor()
    }
    fun displayAuthor(){
        val author1=Authors("","Trevor Noah","Born of a Crime","2046/575"," Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration.","https://images.unsplash.com/photo-1573488721809-e0f256ad3ad8?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bm92ZWxzfGVufDB8fDB8fHww "," ")
        val author2=Authors("","John Keriamete","My life in crime","2046/575","John was a renowned bank robber back in the day and I can comfortably say that he did quite well as a robber. The book which is 234 pages long was originally published in 1984 but was later published by Spear publishers in 1990. He was the son to Anne Wanjiru, a teacher in Muran’ga, but both his parents were siblings. He started his vice after he dropped out of school and ran away from home to Nairobi to fend for himself and started as a pick pocket and later climbed the ladder to becoming a gang leader. He was then arrested in November 1970 on the eve of his wedding and was charged and imprisoned on 6th January 1971.","https://images.unsplash.com/photo-1705721357357-ab87523248f7?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGtlbnlhbiUyMGJvb2tzfGVufDB8fDB8fHww "," ")
        val author3=Authors("","Ngugi","I will marry when I want","2046/575"," Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration.","https://images.unsplash.com/photo-1598618023885-19ba276b562f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGtlbnlhbiUyMGJvb2tzfGVufDB8fDB8fHww "," ")
        val author4=Authors("","Ngugi","I will marry when I want","2046/575","  Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration.","https://images.unsplash.com/photo-1706469980815-e2c54ace4560?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG9wZW5lZCUyMG5vdmVsc3xlbnwwfHwwfHx8MA%3D%3D "," ")
        val author5=Authors("","Ngugi","I will marry when I want","2046/575"," Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration.","https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D "," ")
        val author6=Authors("","Ngugi","I will marry when I want","2046/575"," Gĩcaamba and Njooki leave, and their wealthy guests arrive: Kĩoi Mũhũũni, who wishes to purchase the land that Kĩgũũnda owns, and his wife, Jezebel, as well as another couple. Kĩgũũnda worries that Kĩoi will bring up the land again, but instead Kĩoi focuses on religion. He tells Kĩgũũnda that he should marry Wangeci in the Christian Church to legitimize their marriage. This upsets Kĩgũũnda and Wangeci, and Kĩgũũnda becomes passionate in his disagreement.After Kĩoi and the others leave, however, Kĩgũũnda and Wangeci discuss matters and decide that if they were to marry in the Christian Church, Kĩoi would have no objection","https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D "," ")
        val author7=Authors("","Ngugi","I will marry when I want","2046/575","  Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration.","https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D "," ")
        val author8=Authors("","Ngugi","I will marry when I want","2046/575"," Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration."," https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D"," ")
        val author9=Authors("","Ngugi","I will marry when I want","2046/575","  Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration."," https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D"," ")
        val author10=Authors("","Ngugi","I will marry when I want","2046/575","  Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration."," https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D"," ")
        val author11=Authors("","Ngugi","I will marry when I want","2046/575","  Another theme is identity and belonging. Trevor Noah explores his mixed-race heritage and the challenges he faced in a society .He reflects on his struggles to find his place and identity in a divided society and the importance of embracing one's true self.   Humor and resilience are also prominent themes. Despite the hardships he faced, Trevor Noah uses humor as a coping mechanism. He shares funny anecdotes and stories that demonstrate his resilience and ability to find joy even in difficult circumstances. It's a powerful memoir that sheds light on important social issues while also providing moments of laughter and inspiration."," https://images.unsplash.com/photo-1514467159223-eae20502f859?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG9wZW5lZCUyMGJvb2t8ZW58MHx8MHx8fDA%3D"," ")
val myauthors= listOf(author1,author2,author3,author4,author5,author6,author7,author8,author9,author10,author11)
        val authorsAdapter=AuthorsAdapter(myauthors)
        binding.rvInfo.adapter=authorsAdapter
    }
}